# Copyright (c) 2026, Earth Trading and contributors
# License: MIT. See license.txt

"""Custom fields for Lead, Opportunity, Quotation, Sales Order, Project."""

CUSTOM_FIELDS = {
	"Lead": [
		{
			"fieldname": "custom_et_trading_section",
			"fieldtype": "Section Break",
			"label": "Trading details",
			"insert_after": "status",
			"collapsible": 1,
		},
		{
			"fieldname": "custom_et_sales_stage",
			"fieldtype": "Select",
			"label": "Sales Stage",
			"options": "Lead\nQualified\nNegotiation\nWon\nLost",
			"default": "Lead",
			"insert_after": "custom_et_trading_section",
			"in_list_view": 1,
			"in_standard_filter": 0,
		},
		{
			"fieldname": "custom_et_lead_function",
			"fieldtype": "Link",
			"options": "ET Lead Function",
			"label": "Lead Function",
			"insert_after": "custom_et_sales_stage",
			"in_list_view": 1,
			"in_standard_filter": 1,
		},
		{
			"fieldname": "custom_et_commodity_group",
			"fieldtype": "Link",
			"options": "Item Group",
			"label": "Commodity Group",
			"insert_after": "custom_et_lead_function",
			"in_list_view": 1,
			"in_standard_filter": 1,
		},
		{
			"fieldname": "custom_et_assigned_trader",
			"fieldtype": "Link",
			"options": "User",
			"label": "Assigned Trader",
			"insert_after": "custom_et_commodity_group",
		},
		{
			"fieldname": "custom_et_brokers_cb",
			"fieldtype": "Column Break",
			"insert_after": "custom_et_assigned_trader",
		},
		{
			"fieldname": "custom_et_internal_broker",
			"fieldtype": "Link",
			"options": "User",
			"label": "Internal Broker",
			"insert_after": "custom_et_brokers_cb",
			"in_standard_filter": 0,
		},
		{
			"fieldname": "custom_et_external_broker",
			"fieldtype": "Link",
			"options": "Supplier",
			"label": "External Broker",
			"insert_after": "custom_et_internal_broker",
			"in_list_view": 1,
			"in_standard_filter": 0,
		},
		{
			"fieldname": "custom_et_region",
			"fieldtype": "Data",
			"label": "Region",
			"insert_after": "custom_et_external_broker",
			"hidden": 1,
		},
		{
			"fieldname": "custom_et_deal_type",
			"fieldtype": "Select",
			"label": "Deal Type",
			"options": "\nBrokerage\nPrincipal",
			"insert_after": "custom_et_region",
			"in_standard_filter": 0,
		},
		{
			"fieldname": "custom_et_incoterm",
			"fieldtype": "Link",
			"options": "Incoterm",
			"label": "Incoterm",
			"insert_after": "custom_et_deal_type",
		},
		{
			"fieldname": "custom_et_trade_report_section",
			"fieldtype": "Section Break",
			"label": "Trade Report",
			"insert_after": "custom_et_incoterm",
			"collapsible": 1,
			"description": (
				"Past trades this lead has done. Request the Data team via the comments section "
				"to include number of transactions per commodity for better understanding of "
				"buyer / seller size, main commodities, and what to focus on or use for further "
				"discussion or development."
			),
		},
		{
			"fieldname": "custom_et_trade_report",
			"fieldtype": "Table",
			"label": "Report",
			"options": "ET Lead Trade Report",
			"insert_after": "custom_et_trade_report_section",
		},
	],
	"Opportunity": [
		{
			"fieldname": "custom_et_trading_section",
			"fieldtype": "Section Break",
			"label": "Trading details",
			"insert_after": "territory",
			"collapsible": 1,
		},
		{
			"fieldname": "custom_et_assigned_trader",
			"fieldtype": "Link",
			"options": "User",
			"label": "Assigned Trader",
			"insert_after": "custom_et_trading_section",
		},
		{
			"fieldname": "custom_et_deal_type",
			"fieldtype": "Select",
			"label": "Deal Type",
			"options": "\nBrokerage\nPrincipal",
			"insert_after": "custom_et_assigned_trader",
		},
	],
	"Customer": [
		{
			"fieldname": "custom_et_party_section",
			"fieldtype": "Section Break",
			"label": "Group & hierarchy",
			"insert_after": "territory",
			"collapsible": 1,
		},
		{
			"fieldname": "custom_et_parent_customer",
			"fieldtype": "Link",
			"options": "Customer",
			"label": "Parent company",
			"description": "Associated / parent buyer in a group structure",
			"insert_after": "custom_et_party_section",
		},
		{
			"fieldname": "custom_et_emails_section",
			"fieldtype": "Section Break",
			"label": "Trade emails & team",
			"insert_after": "custom_et_parent_customer",
			"collapsible": 1,
		},
		{
			"fieldname": "custom_et_emails_quick",
			"fieldtype": "Small Text",
			"label": "Add Emails (one per line)",
			"description": "Quick-add: one email per line. On save they are added to the Emails table below — the first becomes the primary / 'To' if none is set yet.",
			"insert_after": "custom_et_emails_section",
			"allow_in_quick_entry": 1,
		},
		{
			"fieldname": "custom_et_emails",
			"fieldtype": "Table",
			"label": "Emails",
			"options": "ET Party Email",
			"description": "Trade emails for this customer. Tick Primary for the 'To' address(es); the rest are CC'd.",
			"insert_after": "custom_et_emails_quick",
		},
		{
			"fieldname": "custom_et_dealing_users",
			"fieldtype": "Table",
			"label": "Dealing Users",
			"options": "ET Party User",
			"description": "Internal users who deal with this customer (CC'd on trade emails).",
			"insert_after": "custom_et_emails",
		},
		{
			"fieldname": "custom_et_bank_section",
			"fieldtype": "Section Break",
			"label": "Bank Accounts",
			"insert_after": "custom_et_dealing_users",
			"collapsible": 1,
		},
		{
			"fieldname": "custom_et_bank_accounts",
			"fieldtype": "Table",
			"label": "Bank Accounts",
			"options": "ET Bank Account",
			"description": "Bank / wire-transfer details for this customer. Tick Primary for the main account.",
			"insert_after": "custom_et_bank_section",
		},
	],
	"Supplier": [
		{
			"fieldname": "custom_et_party_section",
			"fieldtype": "Section Break",
			"label": "Group & hierarchy",
			"insert_after": "supplier_group",
			"collapsible": 1,
		},
		{
			"fieldname": "custom_et_parent_supplier",
			"fieldtype": "Link",
			"options": "Supplier",
			"label": "Parent company",
			"description": "Associated / parent supplier in a group structure",
			"insert_after": "custom_et_party_section",
		},
		{
			"fieldname": "custom_et_emails_section",
			"fieldtype": "Section Break",
			"label": "Trade emails & team",
			"insert_after": "custom_et_parent_supplier",
			"collapsible": 1,
		},
		{
			"fieldname": "custom_et_emails_quick",
			"fieldtype": "Small Text",
			"label": "Add Emails (one per line)",
			"description": "Quick-add: one email per line. On save they are added to the Emails table below — the first becomes the primary / 'To' if none is set yet.",
			"insert_after": "custom_et_emails_section",
			"allow_in_quick_entry": 1,
		},
		{
			"fieldname": "custom_et_emails",
			"fieldtype": "Table",
			"label": "Emails",
			"options": "ET Party Email",
			"description": "Trade emails for this supplier. Tick Primary for the 'To' address(es); the rest are CC'd.",
			"insert_after": "custom_et_emails_quick",
		},
		{
			"fieldname": "custom_et_dealing_users",
			"fieldtype": "Table",
			"label": "Dealing Users",
			"options": "ET Party User",
			"description": "Internal users who deal with this supplier (CC'd on trade emails).",
			"insert_after": "custom_et_emails",
		},
		{
			"fieldname": "custom_et_bank_section",
			"fieldtype": "Section Break",
			"label": "Bank Accounts",
			"insert_after": "custom_et_dealing_users",
			"collapsible": 1,
		},
		{
			"fieldname": "custom_et_bank_accounts",
			"fieldtype": "Table",
			"label": "Bank Accounts",
			"options": "ET Bank Account",
			"description": "Bank / wire-transfer details for this supplier. Tick Primary for the main account.",
			"insert_after": "custom_et_bank_section",
		},
	],
	"Quotation": [
		{
			"fieldname": "custom_et_trading_section",
			"fieldtype": "Section Break",
			"label": "Trading details",
			"insert_after": "incoterm",
			"collapsible": 1,
		},
		{
			"fieldname": "custom_et_assigned_trader",
			"fieldtype": "Link",
			"options": "User",
			"label": "Assigned Trader",
			"insert_after": "custom_et_trading_section",
		},
		{
			"fieldname": "custom_et_deal_type",
			"fieldtype": "Select",
			"label": "Deal Type",
			"options": "\nBrokerage\nPrincipal",
			"insert_after": "custom_et_assigned_trader",
		},
		{
			"fieldname": "custom_et_revision_no",
			"fieldtype": "Int",
			"label": "Revision No",
			"default": "1",
			"read_only": 1,
			"no_copy": 0,
			"insert_after": "custom_et_deal_type",
		},
	],
	"Sales Order": [
		{
			"fieldname": "custom_et_trading_section",
			"fieldtype": "Section Break",
			"label": "Trading details",
			"insert_after": "incoterm",
			"collapsible": 1,
		},
		{
			"fieldname": "custom_et_assigned_trader",
			"fieldtype": "Link",
			"options": "User",
			"label": "Assigned Trader",
			"description": "The other trader on this deal. The order's creator is the first trader; when an Assigned Trader is set the commission is split 50/50 between them.",
			"insert_after": "custom_et_trading_section",
		},
		{
			"fieldname": "custom_et_deal_type",
			"fieldtype": "Select",
			"label": "Deal Type",
			"options": "\nBrokerage\nPrincipal",
			"insert_after": "custom_et_assigned_trader",
		},
		# --- Top section additions to match the operations layout ----------
		# Standard SO already has 3 columns in the Customer section
		# (column_break_7 between order_type and transaction_date, and
		# column_break1 between delivery_date and po_no). Just slot Supplier
		# under order_type (col 1) and Contract Type under po_date (col 3).
		# Trading roles: the standard `customer` field is the BUYER, and this
		# Supplier field is the SELLER.
		{
			"fieldname": "custom_et_supplier",
			"fieldtype": "Link",
			"options": "Supplier",
			"label": "Supplier",
			"description": "Seller / supplier of the trade (the Customer is the buyer).",
			"insert_after": "order_type",
			"reqd": 1,
			"in_list_view": 1,
			"in_standard_filter": 1,
		},
		{
			"fieldname": "custom_et_contract_type",
			"fieldtype": "Select",
			"label": "Contract Type",
			"options": "\nBrokerage\nDirect (Back to Back)\nTo Seller\nTo Buyer",
			"insert_after": "po_date",
			"reqd": 1,
			"in_standard_filter": 1,
		},
		{
			"fieldname": "custom_et_operations_section",
			"fieldtype": "Section Break",
			"label": "Operations",
			"insert_after": "custom_et_deal_type",
			"collapsible": 0,
		},
		{
			"fieldname": "custom_et_brokerage_commission_value",
			"fieldtype": "Float",
			"label": "Brokerage Commission Value",
			"description": "Per-Metric-Ton brokerage commission. Shown in the Seller email only.",
			"insert_after": "custom_et_operations_section",
			"reqd": 0,
		},
		{
			"fieldname": "custom_et_co_brokerage_commission_value",
			"fieldtype": "Float",
			"label": "Co-Brokerage Commission Value",
			"default": "0",
			"insert_after": "custom_et_brokerage_commission_value",
			"reqd": 0,
			"hidden": 0,
		},
		{
			"fieldname": "custom_et_insurance_value",
			"fieldtype": "Float",
			"label": "Insurance Value",
			"default": "0",
			"insert_after": "custom_et_co_brokerage_commission_value",
			"reqd": 0,
			"hidden": 1,
		},
		{
			"fieldname": "custom_et_trade_payment",
			"fieldtype": "Link",
			"options": "Payment Terms Template",
			"label": "Trade Payment",
			"description": "Payment terms shown in the trade email.",
			"insert_after": "custom_et_insurance_value",
			"reqd": 1,
		},
		{
			"fieldname": "custom_et_origin",
			"fieldtype": "Link",
			"options": "Country",
			"label": "Origin",
			"insert_after": "custom_et_trade_payment",
			"reqd": 1,
		},
		{
			"fieldname": "custom_et_port_of_loading",
			"fieldtype": "Link",
			"options": "ET Port",
			"label": "Port Of Loading",
			"insert_after": "custom_et_origin",
			"reqd": 1,
		},
		{
			"fieldname": "custom_et_operations_cb",
			"fieldtype": "Column Break",
			"insert_after": "custom_et_port_of_loading",
		},
		{
			"fieldname": "custom_et_packaging_design",
			"fieldtype": "Select",
			"label": "Packaging Design",
			"options": "\nSeller's Design\nBuyer's Design\nNeutral",
			"insert_after": "custom_et_operations_cb",
			"reqd": 1,
		},
		{
			"fieldname": "custom_et_crop",
			"fieldtype": "Data",
			"label": "Crop",
			"description": "Crop year (e.g. 2024).",
			"insert_after": "custom_et_packaging_design",
			"reqd": 1,
		},
		{
			"fieldname": "custom_et_destination",
			"fieldtype": "Link",
			"options": "Country",
			"label": "Destination",
			"insert_after": "custom_et_crop",
			"reqd": 1,
		},
		{
			"fieldname": "custom_et_port_of_destination",
			"fieldtype": "Link",
			"options": "ET Port",
			"label": "Port of Destination",
			"insert_after": "custom_et_destination",
			"reqd": 1,
		},
		# --- Email recipients ------------------------------------------------
		# Auto-filled from the selected Customer + Supplier (see
		# earthentrading.api.recipients). Each row is tagged Customer/Supplier
		# and carries editable Primary (To) / CC ticks; the trade-confirmation
		# email's To/CC is built from this table.
		{
			"fieldname": "custom_et_email_section",
			"fieldtype": "Section Break",
			"label": "Email Recipients",
			"insert_after": "custom_et_port_of_destination",
			"collapsible": 1,
			"description": (
				"Auto-filled from the Customer and Supplier when selected: primary email (To), "
				"secondary email and connected users (CC). Tick Primary / CC per row; "
				"a row with neither ticked is not emailed."
			),
		},
		{
			"fieldname": "custom_et_email_recipients",
			"fieldtype": "Table",
			"label": "Recipients",
			"options": "ET Email Recipient",
			"insert_after": "custom_et_email_section",
		},
	],
	"Sales Order Item": [
		{
			"fieldname": "custom_et_container",
			"fieldtype": "Data",
			"label": "Container",
			"description": "e.g. 2x20FCL — shown next to quantity in the trade email.",
			"insert_after": "item_name",
			"in_list_view": 0,
		},
		{
			"fieldname": "custom_et_packaging",
			"fieldtype": "Data",
			"label": "Packaging",
			"insert_after": "custom_et_container",
			"in_list_view": 0,
		},
		{
			"fieldname": "custom_et_shipping_start",
			"fieldtype": "Date",
			"label": "Shipping Start",
			"insert_after": "custom_et_packaging",
			"in_list_view": 1,
			"columns": 1,
		},
		{
			"fieldname": "custom_et_shipping_end",
			"fieldtype": "Date",
			"label": "Shipping End",
			"insert_after": "custom_et_shipping_start",
			"in_list_view": 1,
			"columns": 1,
		},
		{
			"fieldname": "custom_et_traded_price",
			"fieldtype": "Currency",
			"label": "Traded Price",
			"insert_after": "rate",
			"in_list_view": 0,
		},
	],
	"Project": [
		{
			"fieldname": "custom_et_checklist_section",
			"fieldtype": "Section Break",
			"label": "Earth Trading checklist",
			"description": (
				"Pick an ET Task Template once per project to create Tasks and assign them to the project team "
				"(or to the assignee chosen on each template line)."
			),
			"insert_after": "project_template",
			"collapsible": 1,
		},
		{
			"fieldname": "custom_et_task_template",
			"fieldtype": "Link",
			"label": "ET Task Template",
			"options": "ET Task Template",
			"insert_after": "custom_et_checklist_section",
		},
		{
			"fieldname": "custom_et_checklist_spawned",
			"fieldtype": "Check",
			"label": "Checklist tasks created",
			"read_only": 1,
			"default": "0",
			"insert_after": "custom_et_task_template",
			"description": "Set automatically after tasks are created from the template (runs once per project).",
		},
	],
	"User": [
		{
			"fieldname": "custom_et_commission_pct",
			"fieldtype": "Percent",
			"label": "Commission %",
			"description": "Earth Trading: this trader's commission rate on deals they create. Applied to the order value to compute the deal's commission (e.g. 10% of 15,000 = 1,500); split 50/50 when an Assigned Trader is set.",
			"insert_after": "user_type",
		},
	],
}
